version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-docker-ansible
    build:
      context: .
      dockerfile: Dockerfile-Jenkins-Docker-ansibler
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
networks:
  net:
