pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                sh '''
                    /var/jenkins_home/workspace/pipeline-docker-maven/pipeline/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    /var/jenkins_home/workspace/pipeline-docker-maven/pipeline/jenkins/build/build.sh
                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'java-app/target/*.jar', fingerprint: true
                }
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/test/mvn.sh mvn test'
            }

            post {
                always {
                    junit 'java-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Push') {
            steps {
                sh './jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh './jenkins/deploy/deploy.sh'
            }
        }
    }
}
