pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                sh '''
                    chmod +x pipeline/jenkins/build/mvn.sh
                    chmod +x pipeline/jenkins/build/build.sh
                    ./pipeline/jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./pipeline/jenkins/build/build.sh 
                '''
            }

            post {
                success {
                   archiveArtifacts artifacts: 'pipeline/java-app/target/*.jar', fingerprint: true
                }
            }
        }

        stage('Test') {
            steps {
                sh '''
                    chmod +x pipeline/jenkins/test/mvn.sh
                    ./pipeline/jenkins/test/mvn.sh mvn test'
                '''
            }

            post {
                always {
                    sh 'pwd'
                    junit './java-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Push') {
            steps {
                sh './jenkins/push/push.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh './jenkins/deploy/deploy.sh'
            }
        }
    }
}
